# Generated by Django 5.0.7 on 2024-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("messages", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
