# Generated by Django 5.0.7 on 2024-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_api", "0002_whatsappchathistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappchathistory",
            name="messages",
            field=models.JSONField(default=list),
        ),
    ]
